spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=bt10;encrypt=true;trustServerCertificate=true
    username: sa
    password: yourStrong(!)Password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  thymeleaf:
    cache: false

server:
  port: 8080